"use client";

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import "../styles/reset.css";
import StyledComponentsRegistry from "./registry";
import styled, { ThemeProvider } from "styled-components";
import theme from "../styles/theme";

const inter = Inter({ subsets: ["latin"] });

// const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <ThemeProvider theme={theme}>
          <Layout className={inter.className}>
            <Main>{children}</Main>
          </Layout>
        </ThemeProvider>
      </StyledComponentsRegistry>
    </html>
  );
}

const Layout = styled.body`
  max-width: ${theme.maxWidth};
  background-color: ${theme.background};
  margin: auto;
`;

const Main = styled.main`
  display: flex;
  flex-direction: column;
  align-items: center;
  min-height: 100vh;
  justify-content: space-between;
  padding: 6rem;
  position: relative;
`;
