'use client';

// import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import '../styles/globals.css';
import '../styles/reset.css';
import StyledComponentsRegistry from './registry';
import styled, { ThemeProvider } from 'styled-components';
import theme from '../styles/theme';

const inter = Inter({ subsets: ['latin'] });

// const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <StyledComponentsRegistry>
        <ThemeProvider theme={theme}>
          <Layout className={inter.className}>{children}</Layout>
        </ThemeProvider>
      </StyledComponentsRegistry>
    </html>
  );
}

const Layout = styled.body`
  width: 100%;
  height: 100vh;
  padding: 20px;
  margin: auto;
  position: relative;
  display: flex;
  flex-direction: column;
  background-color: ${theme.extraWhite};
  max-width: ${theme.maxWidth};
`;
